# Generated by Django 4.2.11 on 2024-05-04 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "restraun",
            "0002_remove_booking_comment_remove_booking_guest_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 4, 15, 11, 6, 422276)
            ),
        ),
    ]
