# Generated by Django 4.2.11 on 2024-05-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restraun", "0007_alter_booking_reservation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(),
        ),
    ]
